### ISSUE TITLE
better-discord fails to install: unable to connect to github.com

### ISSUE THREAD

**Issue by theCapypara** [Half-Shot/matrix-appservice-discord#803]
**Describe the bug**
It's not possible to install a stable version of the bridge, because 1.0.0 and master are still using git://github.com for dependencies, which Github stopped providing earlier this year.

**To Reproduce**
1. Clone the repo
2. Checkout master or v1.0.0
3. Try running npm install or yarn install

**Expected behavior**
I expect the dependencies to install.

**Additional context**
The error message (by yarn):

```
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/Sorunome/better-discord.js.git
Directory: /home/marco/discord-bridge/matrix-appservice-discord
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Connection timed out
```

**Comment by Miepee** [comment]
Note that this has been fixed by d09c78a2403e3e622a862f56c6474e6b8a1673a6 in `develop`
I don't know if `master` is still a supported branch, but a new release sounds helpful considering the last one is almost 1.5years old.

**Comment by jaller94** [comment]
## Tasks
* Publish a new release.

**Comment by jaller94** [comment]
Solved by the release of v2.0.0.

**Comment by jaller94** [comment]
Actually, I still see this a lot, on CI and my local dev machine. I don't think it's fixed.

**Comment by Vyquos** [comment]
Most recent update to `yarn.lock` is commit bfd6bbd.

**Comment by jaller94** [comment]
Run `git config --global url.https://github.com/.insteadOf git://github.com/`.

The issue seems to be that github deprecated the port for `git://`.
https://github.com/npm/npm/issues/6285
Not really sure how to deal with this. It's bad if it doesn't work without changing some configuration change.

The PR https://github.com/matrix-org/matrix-appservice-discord/pull/777 didn't fix this.
