### ISSUE TITLE
[M>D] 'M_USER_IN_USE' error; likely related to how matrix-bot-sdk handles registration checks

### ISSUE THREAD

**Issue by msglm** [Half-Shot/matrix-appservice-discord#894]
Due to hacky fixes I have attempted to use while solving #864, I often end up having to go-through the install process of this program multiple times. This includes dropping the database entirely (before [this hack](https://github.com/matrix-org/matrix-appservice-discord/issues/864#issuecomment-1288247116) was discovered as a temporary solution) and re-creating the appservice registration file.
Because of these hacky fixes, matrix-appservice-discord often attempts to re-register the account used for bridging and reviving matrix commands on the homeserver. It fails at doing this and is unable to send messages or receive messages on either side. I could not find the line of code where this happens in the software itself, but the error that corresponds with it:
```
Aug-19 06:52:21.258 [bot-sdkMatrixHttpClient] error: [
  '(REQ-1)',
  { errcode: 'M_USER_IN_USE', error: 'User ID already taken.' }
]
```
Is the designated error that comes from `ensuredRegistered()` in [matrix-bot-sdk](https://github.com/turt2live/matrix-bot-sdk/blob/main/src/appservice/Intent.ts#L306). This implies that there is no handling for attempting to access the already-registered matrix-appservice-discord account on a homeserver (if such a thing is even possible).

This problem may be reproducible in more normal circumstances, such as migrating the location of a matrix-appservice-discord bot without migrating the database over, or in situations where a user desires to use a fork of this software.

Steps to reproduce:
1. Follow the setup instructions until a proper bridge between discord and matrix is working
2. Turn off the bridge
3. Delete the databases related to matrix-discord-appservice
4. remove the discord-registration.yaml file in both the homeserver and source code repo
5. Follow the setup instructions again from the start
6. Upon startup, matrix-discord-appservice should comment about a "M_USER_IN_USE" problem.

Hack workarounds:
None Yet.

Possibly Related Issues:
#840
#835 (different bot library(?), same error)
#37 (Old, possibly unrelated; same error however)

**Comment by msglm** [comment]
From my research, this bug seems to be caused by [this line](https://github.com/turt2live/matrix-bot-sdk/blob/c46efe7e7ba6d8870e304ab53e54dd8157b241e9/src/appservice/Intent.ts#L322) failing to return true. What causes this to be exact is not something I can figure out since I do not know javascript or the project itself too well.

**Comment by msglm** [comment]
Fixed the issue:
If you're running Synapse 1.90 (and perhaps greater), you will need to enable legacy auth, since this project uses it.
adding `use_appservice_legacy_authorization: true`  to the matrix synapse server re-enables legacy auth.
documentation on the subject: https://matrix-org.github.io/synapse/latest/upgrade#upgrading-to-v1900

**Comment by MattyBoombalatty** [comment]
I am having the same issue. I had to remake the `discord-registration.yaml` file but left the database untouched so I didn't have to re-bridge all of the rooms and now the messages come through fine, but they're not being displayed as the Discord user name in Matrix, just the tag set in the registration yaml file followed by a random set of numbers.

**Comment by pilot51** [comment]
I'm having this issue.

I tried setting this up a couple years ago and gave up in favor of t2bot, then last week they [accidentally lost everything](https://t2bot.io/blog/2024/01/14/discord-bridge-reset) and all bridges need to be set up again. So I'm taking the opportunity to try self-hosting again.

Unfortunately, the old bot user still exists and can't (or [really shouldn't](https://github.com/matrix-org/synapse/issues/1707#issuecomment-1001100237)) be deleted and recreated, and I've since deleted the original appservice database. I would like to use the existing default `_discord_bot` user instead of letting it stay a ghost forever and creating an uglier one like `_discord_bot2`.

I tried adding `use_appservice_legacy_authorization: true` to `homeserver.yaml` and it didn't change anything.

Looking at the Synapse database, it appears it may be possible for an appservice to log into an existing user as long as `id` in the registration file matches `appservice_id` in the `users` table, but the appservice gives up instead of trying to use the existing user.
